name: Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: |
          npm install

      - name: Run Build
        run: |
          npm run build

  markdown-spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Spell Check
        uses: docker://registry.gitlab.com/pipeline-components/markdown-spellcheck:latest
        with:
          entrypoint: ["mdspell"]
          args: ["--report", "'**/*.md'"]
